#!/usr/bin/env python3
"""Generate or verify a compact first-party code inventory."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/generated/codebase-inventory.md"
EXCLUDED_PARTS = {".git", ".venv", "runtime", "vendor", "__pycache__", ".agents", ".codex"}
SOURCE_SUFFIXES = {".py", ".sh", ".toml", ".json", ".sql"}


def inventory() -> list[tuple[str, int, str]]:
    rows: list[tuple[str, int, str]] = []
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or EXCLUDED_PARTS.intersection(path.relative_to(ROOT).parts):
            continue
        if (
            path == OUTPUT
            or path.name == "release-manifest.json"
            or (path.suffix not in SOURCE_SUFFIXES and path.name != "VERSION")
        ):
            continue
        data = path.read_bytes()
        rows.append(
            (
                path.relative_to(ROOT).as_posix(),
                data.count(b"\n") + bool(data),
                hashlib.sha256(data).hexdigest(),
            )
        )
    return rows


def digest(rows: list[tuple[str, int, str]]) -> str:
    material = "\n".join(f"{path}\0{size}\0{sha}" for path, size, sha in rows)
    return hashlib.sha256(material.encode("utf-8")).hexdigest()


def render(rows: list[tuple[str, int, str]]) -> str:
    groups: dict[str, list[tuple[str, int, str]]] = {}
    for row in rows:
        groups.setdefault(row[0].split("/", 1)[0], []).append(row)
    lines = [
        "# Generated codebase inventory",
        "",
        "This file is generated by `scripts/codebase_inventory.py`; do not edit it manually.",
        f"Source digest: `{digest(rows)}`",
        f"First-party source artifacts: **{len(rows)}**",
        "",
        "| Area | Files | Lines |",
        "| --- | ---: | ---: |",
    ]
    for area, values in sorted(groups.items()):
        lines.append(f"| `{area}` | {len(values)} | {sum(row[1] for row in values)} |")
    lines.extend(
        ("", "## Largest Python modules", "", "| File | Lines | Digest |", "| --- | ---: | --- |")
    )
    for path, count, sha in sorted(
        (row for row in rows if row[0].endswith(".py")), key=lambda row: row[1], reverse=True
    )[:25]:
        lines.append(f"| `{path}` | {count} | `{sha[:12]}` |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    expected = render(inventory())
    if args.verify:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("generated codebase inventory is stale")
            return 1
        print("generated codebase inventory verified")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
